api/urls.py
from django.urls import path

from .views import EnciclopediaList, ArtigoDetail, CategoriaDetail, CategoriaList


urlpatterns = [
    path('enciclopedia/<int:pk>/', ArtigoDetail.as_view()),
    path('enciclopedia/', EnciclopediaList.as_view()),
    path('categoria/<int:pk>/', CategoriaDetail.as_view()),
    path('categoria/', CategoriaList.as_view()),
]

petersite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('pets/', include('pets.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls')),

]

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'
urlpatterns = [
    # path('login/', views.login, name='login'),
    path('animais/<int:pk>/', views.PetUpdateView.as_view(), name='singlepet'),
    path('animais/', views.PetListView.as_view(), name='petlist'),
    path('clinicalist/', views.ClinicaListView.as_view(), name='clinicalist'),
    path('veterinarios/', views.VetListView.as_view(), name='vetlistpets'),
    path('lembrete/', views.LembreteView.as_view(), name='lembrete'),
    path('inserlembrete/', views.create_lembrete, name='inserlembrete'),
    path('banco/', views.BancoView.as_view(), name='banco'),
    
    # path('<int:pk>/', views.PetDetailView.as_view(), name='principal'),
    path('criar/', views.create_pet, name='createpet'),
    path('criar/dono/', views.create_donopet, name='createdono'),
    path('criar/vet/', views.create_vet, name='createvet'),
    path('criar/clinica/', views.create_clinica, name='createclinica'),
    path('<int:pk>/', views.PetDetailView.as_view(), name='singlepetdetail'),
    path('dono/', views.DonoView.as_view(), name='dono'),
    path('vet/', views.VetView.as_view(), name='vet'),
    path('clinica/', views.ClinicaView.as_view(), name='clinica'),
    path('agenda/', views.AgendaView.as_view(), name='agenda'),
    path('inseragenda/', views.AgendaUpdateView.as_view(), name='inseragenda'),
    path('historico/<int:pk>', views.HistoricoDetailView.as_view(), name='singlepethistorico'),
    path('inserehistorico/<int:pet_id>', views.create_historico, name='inserehistorico'),
    path('enciclopedia/', views.EnciclopediaListView.as_view(), name='enciclopedia'),
    path('enciclopedia/<int:pk>/', views.ArtigoDetailView.as_view(), name='artigo'),

    path('search/', views.search_all, name='search'), 
    
    
]

pets/models.py
from django.db import models
from django.conf import settings
from datetime import datetime
from django.urls import reverse

class Animal(models.Model):
    
    name = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.name}'

class Donopet(models.Model):
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, blank=True)
    endereco = models.CharField(max_length=255, blank=True)
    bairro = models.CharField(max_length=255, blank=True)
    municipio = models.CharField(max_length=255, blank=True)
    estado = models.CharField(max_length=255, blank=True)
    cpf = models.CharField(max_length=255, blank=True)
    celular = models.CharField(max_length=255, blank=True)
    genero = models.CharField(max_length=255, blank=True)
    data_de_nascimento = models.DateTimeField()
    imagem = models.CharField(max_length=255)

    class Meta:
        permissions = [
            ("criar_pet","Pode criar um pet"),
            ("ver_dono","Pode ver páginas exclusivas de um dono de pet"),
            ("dono_ver_pet", "Dono pode ver seus pets"),
            ("preencher_forms_completar_signup_dono", "Pode preencher o forms com as informações de um dono de pet"),
        ]

    def __str__(self):
        return f'{self.usuario}'


class Veterinario(models.Model):
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, blank=True)
    endereco = models.CharField(max_length=255, blank=True)
    bairro = models.CharField(max_length=255, blank=True)
    municipio = models.CharField(max_length=255, blank=True)
    estado = models.CharField(max_length=255, blank=True)
    cpf = models.CharField(max_length=255, blank=True)
    celular = models.CharField(max_length=255, blank=True)
    genero = models.CharField(max_length=255, blank=True)
    data_de_nascimento = models.DateTimeField()
    imagem = models.CharField(max_length=255)
    agenda = models.CharField(max_length=255, blank=True)
    dono = models.ManyToManyField(Donopet)

    class Meta:
        permissions = [
            ("vet_ver_pet", "Vet pode ver seus pets"),
            ("ver_vet","Pode ver páginas exclusivas de um veterinario"),
            ("preencher_forms_completar_signup_vet", "Pode preencher o forms com as informações de um veterinario"),
        ]

    def __str__(self):
        return f'{self.usuario}'


class Clinica(models.Model):
    usuario = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nome = models.CharField(max_length=255, blank=True)
    endereco = models.CharField(max_length=255, blank=True)
    bairro = models.CharField(max_length=255, blank=True)
    municipio = models.CharField(max_length=255, blank=True)
    estado = models.CharField(max_length=255, blank=True)
    cnpj = models.CharField(max_length=255, blank=True)
    telefone = models.CharField(max_length=255, blank=True)
    cnae = models.CharField(max_length=255, blank=True)
    razao_social = models.CharField(max_length=255, blank=True)
    imagem = models.CharField(max_length=255)
    nome_fantasia = models.CharField(max_length=255, blank=True)
    vet = models.ManyToManyField(Veterinario)

    class Meta:
        permissions = [
            ("clinica_ver_pet", "Clinica pode ver seus pets"),
            ("ver_clinica","Pode ver páginas exclusivas de uma clinica"),
            ("preencher_forms_completar_signup_clinica", "Pode preencher o forms com as informações de uma clinica"),
        ]

    def __str__(self):
        return f'{self.usuario}'

class Pet(models.Model):
    dono = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    tipo_sanguineo = models.CharField(max_length=255, blank=True)
    raca = models.CharField(max_length=255, blank=True)
    imagem = models.URLField(max_length=255, null=True, blank=True)
    data_de_nascimento = models.DateTimeField()

    tipo_animal = models.ForeignKey(
        Animal,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'{self.name}'

class Historico(models.Model):
    editor = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    texto = models.CharField(max_length=255)
    data = models.DateTimeField(default=datetime.now)
    pet = models.ForeignKey(Pet, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.data} - ({self.editor}) {self.texto}'


class Atividade(models.Model):
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    vet = models.ForeignKey(Veterinario, on_delete=models.CASCADE, blank=True, null=True)
    clinica = models.ForeignKey(Clinica, on_delete=models.CASCADE, blank=True, null=True)

    nome = models.CharField(max_length=255, blank=True)
    data = models.DateTimeField()
    mensagem = models.CharField(max_length=255, blank=True)


    def __str__(self):
        return f'{self.nome}'


class Categoria(models.Model):
    
    nome = models.CharField(max_length=255)

    def __str__(self):
        return f'{self.nome}'


class Enciclopedia(models.Model):
    
    name = models.CharField(max_length=255)
    assunto = models.CharField(max_length=255)
    conteudo = models.TextField()
    
    tipocategoria = models.ForeignKey(
        Categoria,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return f'{self.name}'

pets/views.py
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic.edit import UpdateView
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .models import Pet, Animal, Donopet, Veterinario, Clinica, Atividade, Historico, Enciclopedia, Categoria
from .forms import PetForm, DonopetForm, VeterinarioForm, ClinicaForm, AtividadeForm, HistoricoForm, VeterinarioparadonoForm
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin




# Create your views here.


class PetUpdateView(LoginRequiredMixin, PermissionRequiredMixin, generic.UpdateView):
    model = Pet
    template_name = 'pets/singlepet.html'
    fields = ['name', 'tipo_sanguineo', 'raca','imagem', 'data_de_nascimento']
    success_url = './'
    permission_required = 'pets.atualizar_pet'

class PetDetailView(LoginRequiredMixin, generic.DetailView):
    model = Pet
    template_name = 'pets/singlepetdetail.html'

class PetListView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/petlist.html'
    success_url = '/animais'

class ClinicaListView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/clinicalist.html'
    success_url = '/clinicalist'
    
class VetListView(LoginRequiredMixin, generic.ListView):
    model = Atividade
    template_name = 'pets/vetlistpets.html'
    success_url = '/veterinarios'

class LembreteView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/lembrete.html'
    success_url = '/pets/lembrete'


def create_lembrete(request):
    if request.method == 'POST':
        form = AtividadeForm(request.POST)
        if form.is_valid():
            atividade = Atividade(**form.cleaned_data) 
            atividade.usuario = request.user
            atividade.save()
           
        return HttpResponseRedirect(
            reverse('pets:lembrete'))
    else:
        form = AtividadeForm()
    context = {'form': form}
    return render(request, 'pets/inserlembrete.html', context)


class DonoView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/dono.html'
    success_url = '/pets/dono'
    permission_required = 'pets.ver_dono'

class VetView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/vet.html'
    success_url = '/pets/vet'
    permission_required = 'pets.ver_vet'

class ClinicaView(LoginRequiredMixin, PermissionRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/clinica.html'
    success_url = '/pets/clinica'
    permission_required = 'pets.ver_clinica'

class AgendaView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/agenda.html'
    success_url = '/pets/agenda'

class AgendaUpdateView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/inseragenda.html'
    success_url = '/pets/inseragenda'

class BancoView(LoginRequiredMixin, generic.ListView):
    model = Pet
    template_name = 'pets/banco.html'
    success_url = '/pets/banco'



class PetCreateView(LoginRequiredMixin, generic.CreateView):
    model = Pet
    fields = ['name', 'tipo_sanguineo', 'raca','imagem', 'data_de_nascimento']
    template_name = 'pets/createpet.html'
    success_url = '/pets/animais'

class DonopetCreateView(LoginRequiredMixin, PermissionRequiredMixin, generic.CreateView):
    model = Donopet
    fields = ['endereco', 'bairro', 'municipio','estado', 'cpf','celular','genero','data_de_nascimento','imagem']
    template_name = 'pets/createdono.html'
    success_url = '/pets/animais'
    permission_required = 'pets.preencher_forms_completar_signup_dono'

@permission_required('pets.preencher_forms_completar_signup_dono')
def create_donopet(request):
    if request.method == 'POST':
        form = DonopetForm(request.POST)
        if form.is_valid():
            donopet = Donopet(**form.cleaned_data) 
            donopet.usuario = request.user
            donopet.save()
           
        return HttpResponseRedirect(
            reverse('pets:dono'))
    else:
        form = DonopetForm()
    context = {'form': form}
    return render(request, 'pets/createdono.html', context)

@permission_required('pets.preencher_forms_completar_signup_vet')
def create_vet(request):
    if request.method == 'POST':
        form = VeterinarioForm(request.POST)
        if form.is_valid():
            veterinario = Veterinario(**form.cleaned_data) 
            veterinario.usuario = request.user
            veterinario.save()
           
        return HttpResponseRedirect(
            reverse('pets:vet'))
    else:
        form = VeterinarioForm()
    context = {'form': form}
    return render(request, 'pets/createvet.html', context)

@permission_required('pets.preencher_forms_completar_signup_clinica')
def create_clinica(request):
    if request.method == 'POST':
        form = ClinicaForm(request.POST)
        if form.is_valid():
            clinica = Clinica(**form.cleaned_data) 
            clinica.usuario = request.user
            clinica.save()
           
        return HttpResponseRedirect(
            reverse('pets:clinica'))
    else:
        form = ClinicaForm()
    context = {'form': form}
    return render(request, 'pets/createclinica.html', context)

def create_historico(request, pet_id):
    pet = get_object_or_404(Pet, pk=pet_id)
    if request.method == 'POST':
        form = HistoricoForm(request.POST)
        if form.is_valid():
            historico = Historico(**form.cleaned_data) 
            historico.editor = request.user
            historico.pet = pet
            historico.save()
            return HttpResponseRedirect(
                reverse('pets:singlepethistorico', args=(pet_id, )))
    else:
        form = HistoricoForm()
    context = {'form': form, 'pet': pet}
    return render(request, 'pets/inserehistorico.html', context)

class HistoricoDetailView(generic.DetailView):
    model = Pet
    template_name = 'pets/singlepethistorico.html'





# def update_historico(request, pet_id, hist_id):
#     pet = get_object_or_404(Pet, pk=pet_id)
#     hist = get_object_or_404(Pet, pk=pet_id)

#     if requested.method == "POST":
#         historico = Historico(**form.cleaned_data) 
#             historico.editor = request.user
#             historico.pet = pet
#             historico.save()
#             return HttpResponseRedirect(
#                 reverse('pets:singlepet', args=(pet_id, )))
#         context = {'pet':pet}
#         return render(request, 'pets/atualizahistorico.html', context)

# def delete_historico(request, pet_id):
#     pet = get_object_or_404(Pet, pk=pet_id)
#     if request.method == "POST":
#         pet.delete()
#         return HttpResponseRedirect(reverse('pets:singlepethistorico'))
#     context = {'pet':pet}
#     return render(request, 'pets/deletehistorico.html', context)
    
    


# class PetCreateView(LoginRequiredMixin, generic.CreateView):
#     model = Pet
#     fields = ['name', 'tipo_sanguineo', 'raca','imagem', 'data_de_nascimento', 'tipo_animal']
#     template_name = 'pets/createpet.html'
#     success_url = '/pets/animais'



@login_required
@permission_required('pets.criar_pet')
def create_pet(request):
    if request.method == 'POST':
        pet_form = PetForm(request.POST)
        if pet_form.is_valid():
            pet = Pet(**pet_form.cleaned_data) 
            pet.dono = request.user
            pet.save()
           
        return HttpResponseRedirect(
            reverse('pets:singlepet', args=(pet.pk, )))
    else:
        pet_form = PetForm()
    context = {'pet_form': pet_form}
    return render(request, 'pets/createpet.html', context)


def search_all(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        pet_list = Pet.objects.filter(name__icontains=search_term)
        vet_list = Veterinario.objects.filter(nome__icontains=search_term)
        clinica_list = Clinica.objects.filter(nome__icontains=search_term)
        context = {"pet_list": pet_list, "vet_list":vet_list, "clinica_list":clinica_list}

    # if request.method == 'POST':
    #     form = AtividadeForm(request.POST)
    #     if form.is_valid():
    #         atividade = Atividade(**form.cleaned_data) 
    #         atividade.usuario = request.user
    #         atividade.vet = request.veterinario
    #         atividade.save()
            
    #     return HttpResponseRedirect(
    #         reverse('pets:lembrete'))
    # else:
    #     form = AtividadeForm()
    # context['form'] = form
    
    return render(request, 'pets/search.html', context)


# def create_lembrete(request):
#     if request.method == 'POST':
#         form = AtividadeForm(request.POST)
#         if form.is_valid():
#             atividade = Atividade(**form.cleaned_data) 
#             atividade.usuario = request.user
#             atividade.save()
           
#         return HttpResponseRedirect(
#             reverse('pets:lembrete'))
#     else:
#         form = AtividadeForm()
#     context = {'form': form}
#     return render(request, 'pets/inserlembrete.html', context)


class EnciclopediaListView(LoginRequiredMixin, generic.ListView):
    model = Enciclopedia
    template_name = 'pets/enciclopedias.html'
    

class ArtigoDetailView(LoginRequiredMixin, generic.DetailView):
    model = Enciclopedia
    template_name = 'pets/artigo.html'

pets/templates/pets/artigo.html
{% extends 'base.html' %}

{% block title %}
{{ enciclopedia.name }}
{% endblock title %}

{% block content %}

<div class="quadradao-lembrete"> 
 
    <section class="cabecalho-lembretes">          
        <img class="agenda-imagem"  src="\static\images\Group 66.png">  
        <div class="child-lembrete-1"> 
            <p class="propaganda-title">{{ enciclopedia.name }}</p> 
            <p class="propaganda-descr"><b>Categoria: </b> {{ enciclopedia.tipocategoria }} </p> 
            <p class="propaganda-descr"><b>Assunto: </b> {{ enciclopedia.assunto }}</p> 
            <p class="propaganda-descr">{{ enciclopedia.conteudo }}</p> 
        </div> 
    </section> 

    {% for objeto in enciclopedia_list %} 
        <section class="comeco-lembretes"> 
            <a class="botao-lembrete botao-lembrete-2"  
            href="{% url 'pets:artigo' objeto.id %}">{{ objeto.name }} (Categoria {{ objeto.tipocategoria }})</a> 
        </section> 
    {% endfor %} 
 
</div> 

{% endblock content %}

pets/templates/pets/clinicalist.html
{% extends 'base.html' %}

{% block title %}
Buscar clínicas veterinárias
{% endblock title %}

{% block content %}




<section class="quadradao-index quadadao-pet">
    <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet pet-coelho"></div>
    <div class="quad-child-texto-index quad-child-texto-pet">
        <p class="propaganda-title">Buscar clínicas veterinárias</p>
        <p class="propaganda-descr"></p>
    </div>
    <!-- <a href="{% url 'pets:createpet' %}" class="botao-pet-cadastro"></a> -->
</section>

{% if clinica_set.all %}
    {% for clinica in clinica_set.all %}
        <section class="quadradao-index quadadao-pet">
            {% if clinica.imagem %}
                <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet"
                style="background: url('{{ clinica.imagem }}') no-repeat center; background-size: cover;"></div>
            {% else %}
                <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet"></div>
            {% endif %}
            <div class="quad-child-texto-index quad-child-texto-pet">
                <p class="propaganda-title">{{ clinica.nome }}</p>
                <p class="propaganda-descr"><b>Telefone: </b> {{ clinica.telefone }}</p>
                <p class="propaganda-descr"><b>CNPJ: </b> {{ clinica.cnpj }}</p>
            </div>
            
        </section>
    {% endfor %}
{% endif %}



{% endblock content %}

pets/templates/pets/dono.html
{% extends 'base.html' %}

{% block title %}
Página de perfil
{% endblock title %}

{% block content %}

<div class="quadradao-user">
    <p class="agenda-title">Bem Vinde ao seu perfil, {{ user.username }} </p>

    <section class="dono-container">
        <a href="{% url 'pets:dono' %}">
            <img src="\static\images\Group 54.png" > 
        </a>
        <a href="{% url 'pets:petlist' %}">
            <img src="\static\images\Group 51.png"> 
        </a>
        <a href="{% url 'pets:search' %}">
            <img src="\static\images\Group 52.png"> 
        </a>
    </section>
    <section class="dono-container">
        <a href="{% url 'pets:dono' %}">
            <img src="\static\images\Group 56.png">
        </a>
        <a href="{% url 'pets:search' %}">
            <img src="\static\images\Group 53.png"> 
        </a>
        <a href="{% url 'pets:enciclopedia' %}">
            <img src="\static\images\Group 55.png">
        </a>
    </section>
</div>

{% endblock content %}

pets/templates/pets/inserehistorico.html
{% extends 'base.html' %}

{% block title %}
{{pet.name}}
{% endblock title %}

{% block content %}
<p class="agenda-title">Adicionar Histórico para {{ pet.name }}</p>

<div class="form-supercontainer">
    <form class="form-container" action="{% url 'pets:inserehistorico' pet.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="botao-form" type="submit">Adicionar Ocorrência</button>
        <a class="botao-form botao-laranja" href="{% url 'pets:singlepethistorico' pet.id %}">Voltar para a página do pet</a>
    </form>
</div>


{% endblock content %}

pets/templates/pets/vet.html
{% extends 'base.html' %}

{% block title %}
Página de perfil
{% endblock title %}

{% block content %}

<div class="quadradao-user">
    <p class="agenda-title">Bem Vinde ao seu perfil, {{ user.username }} </p>

    <section class="dono-container">
        <a href="{% url 'pets:vet' %}">
            <img src="\static\images\Group 54.png" > 
        </a>
        <a href="{% url 'pets:lembrete' %}">
            <img src="\static\images\Group 69.png"> 
        </a>
        <a href="{% url 'pets:vetlistpets' %}">
            <img src="\static\images\Group 70.png"> 
        </a>
    </section>
    <section class="dono-container">
        <a href="{% url 'pets:vet' %}">
            <img src="\static\images\Group 56.png">
        </a>
        <a href="{% url 'pets:clinicalist' %}">
            <img src="\static\images\Group 53.png"> 
        </a>
        <a href="{% url 'pets:enciclopedia' %}">
            <img src="\static\images\Group 55.png">
        </a>
    </section>

</div>
{% endblock content %}

pets/templates/pets/vetlistpets.html
{% extends 'base.html' %}

{% block title %}
Lista de Pets
{% endblock title %}

{% block content %}

<section style="width:100%;">
{% if user.veterinario or user.clinica %}
    
        <section class="quadradao-index quadadao-pet" style="padding: 30px 20px 20px 40px; justify-content: flex-start;">    
            <div>
                {% if user.veterinario %}
                <p class="propaganda-title">Bom dia, veterinário {{ user.veterinario.nome }}</p>
                {% if user.veterinario.atividade_set.all %}
                <p class="propaganda-descr">Você possui os seguintes clientes: </p>
            </div>
        </section>
                {% for atividade in user.veterinario.atividade_set.all %}
                <div style="padding: 0px 0px 0px 40px;">
                    <p class="propaganda-title">Cliente {{ atividade.usuario }}</p>
                    <p class="propaganda-descr">{{ atividade.usuario.donopet.celular }}</p>
                    <p class="propaganda-descr dono-id" style="display: none;">{{ atividade.usuario.donopet.id }}</p>
                    {% if atividade.usuario.pet_set.all %}
                        <p class="propaganda-descr">Que possui os seguintes pets: </p>
                        <br>
                    
                        {% for pet in atividade.usuario.pet_set.all %}
                        <div style="padding: 0px 0px 0px 0px;">

                        <a class="quadradao-index quadadao-pet general-link pet-hover" href="{% url 'pets:singlepetdetail' pet.id %}">    
                            {% if pet.imagem %}
                                <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet"
                                style="background: url('{{ pet.imagem }}') no-repeat center; background-size: cover;"></div>
                            {% else %}
                                <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet"></div>
                            {% endif %}
                            <div class="quad-child-texto-index quad-child-texto-pet">
                                <p class="propaganda-title">{{ pet.name }}</p>
                                <p class="propaganda-descr"><b>Data de Nascimento: </b> {{ pet.data_de_nascimento }}</p>
                                <p class="propaganda-descr"><b>Raça: </b> {{ pet.raca }}</p>
                            </div>
                            <!-- <a href="{% url 'pets:singlepetdetail' pet.id %}" class="botao-pet-cadastro">Consultar dados do Pet</a> -->
                        </a>   

                        </div>                    
                        {% endfor %}
                        <br>
                    
                    {% else %}
                        <p class="propaganda-descr">Que não possui pets cadastrados ainda.</p>
                    </div>
                    {% endif %}  
                </div>         
                {% endfor %}
            {% else %}
                <p class="propaganda-descr">Você não possui clientes cadastrados ainda.</p>
            </div>
        </section>
            {% endif %}


                {% else %}   
                <p class="propaganda-title">Bom dia, clínica {{ user.clinica.nome }}</p>
                      
                {% if user.clinica.atividade_set.all %}
                <p class="propaganda-descr">Você possui os seguintes clientes: </p>
            </div>
        </section>
                {% for atividade in user.clinica.atividade_set.all %}
                <div style="padding: 0px 0px 0px 40px;">
                    <p class="propaganda-title">Cliente {{ atividade.usuario }}</p>
                    <p class="propaganda-descr">{{ atividade.usuario.donopet.celular }}</p>
                    <p class="propaganda-descr dono-id" style="display: none;">{{ atividade.usuario.donopet.id }}</p>
                    {% if atividade.usuario.pet_set.all %}
                        <p class="propaganda-descr">Que possui os seguintes pets: </p>
                        <br>
                    
                        {% for pet in atividade.usuario.pet_set.all %}
                        <div style="padding: 0px 0px 0px 0px;">

                        <a class="quadradao-index quadadao-pet general-link pet-hover" href="{% url 'pets:singlepetdetail' pet.id %}">    
                            {% if pet.imagem %}
                                <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet"
                                style="background: url('{{ pet.imagem }}') no-repeat center; background-size: cover;"></div>
                            {% else %}
                                <div class="quad-child-imagem-index quad-child-imagem-reversed quad-child-imagem-pet"></div>
                            {% endif %}
                            <div class="quad-child-texto-index quad-child-texto-pet">
                                <p class="propaganda-title">{{ pet.name }}</p>
                                <p class="propaganda-descr"><b>Data de Nascimento: </b> {{ pet.data_de_nascimento }}</p>
                                <p class="propaganda-descr"><b>Raça: </b> {{ pet.raca }}</p>
                            </div>
                            <!-- <a href="{% url 'pets:singlepetdetail' pet.id %}" class="botao-pet-cadastro">Consultar dados do Pet</a> -->
                        </a>   

                        </div>                    
                        {% endfor %}
                        <br>
                    
                    {% else %}
                        <p class="propaganda-descr">Que não possui pets cadastrados ainda.</p>
                    </div>
                    {% endif %}  
                </div>         
                {% endfor %}
            {% else %}
                <p class="propaganda-descr">Você não possui clientes cadastrados ainda.</p>
            </div>
        </section>
            {% endif %}
            {% endif %}  
        

{% else %}
    <script>
        window.location.href = "../../";
    </script>


    <!-- <a href="{% url 'pets:createpet' %}">Adicionar animal</a> -->
{% endif %}
</section>

{% endblock content %}