api/urls.py
from django.urls import path

from .views import EnciclopediaList, ArtigoDetail, CategoriaDetail, CategoriaList


urlpatterns = [
    path('enciclopedia/<int:pk>/', ArtigoDetail.as_view()),
    path('enciclopedia/', EnciclopediaList.as_view()),
    path('categoria/<int:pk>/', CategoriaDetail.as_view()),
    path('categoria/', CategoriaList.as_view()),
]

petersite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('staticpages.urls')),
    path('pets/', include('pets.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v1/', include('api.urls')),

]

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'
urlpatterns = [
    # path('login/', views.login, name='login'),
    path('animais/<int:pk>/', views.PetUpdateView.as_view(), name='singlepet'),
    path('animais/', views.PetListView.as_view(), name='petlist'),
    path('clinicalist/', views.ClinicaListView.as_view(), name='clinicalist'),
    path('veterinarios/', views.VetListView.as_view(), name='vetlistpets'),
    path('lembrete/', views.LembreteView.as_view(), name='lembrete'),
    path('inserlembrete/', views.create_lembrete, name='inserlembrete'),
    path('banco/', views.BancoView.as_view(), name='banco'),
    
    # path('<int:pk>/', views.PetDetailView.as_view(), name='principal'),
    path('criar/', views.create_pet, name='createpet'),
    path('criar/dono/', views.create_donopet, name='createdono'),
    path('criar/vet/', views.create_vet, name='createvet'),
    path('criar/clinica/', views.create_clinica, name='createclinica'),
    path('<int:pk>/', views.PetDetailView.as_view(), name='singlepetdetail'),
    path('dono/', views.DonoView.as_view(), name='dono'),
    path('vet/', views.VetView.as_view(), name='vet'),
    path('clinica/', views.ClinicaView.as_view(), name='clinica'),
    path('agenda/', views.AgendaView.as_view(), name='agenda'),
    path('inseragenda/', views.AgendaUpdateView.as_view(), name='inseragenda'),
    path('historico/<int:pk>', views.HistoricoDetailView.as_view(), name='singlepethistorico'),
    path('inserehistorico/<int:pet_id>', views.create_historico, name='inserehistorico'),
    path('enciclopedia/', views.EnciclopediaListView.as_view(), name='enciclopedia'),
    path('enciclopedia/<int:pk>/', views.ArtigoDetailView.as_view(), name='artigo'),

    path('search/', views.search_all, name='search'), 
    
    
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
]

staticpages/models.py
from django.db import models

# Create your models here.

staticpages/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)

staticpages/templates/base.html
{% load static %}

<!DOCTYPE html><html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sofia|Roboto">
    <link rel="stylesheet" href="//db.onlinewebfonts.com/c/febf37ead8b4b5230a74ef82850ffca4?family=LocalBreweryFour-Regular" type="text/css"/>
    <link rel="icon" type="image/png" href="{% static 'icons/Dog.png' %}">
    
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"> <!--usar bootstrap-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="{% static 'form_style.css' %}">
    <link rel="stylesheet" href="{% static 'lem_style.css' %}">
    <link rel="stylesheet" href="{% static 'list_style.css' %}">

    <title>
        {% block title %}{% endblock %} | Peter
    </title>
</head>

<body>
    <header class="menu-container">
        <!-- Canto superior do menu -->
        <nav class="menu-top">
            <div class="menu-top-container">
                <div class="menu-top-side menu-left">
                    <a class="login-button" href="{% url 'index' %}">
                        <div class="round-logo logo-image"></div>
                    </a>  
                    <a class="login-button" id="logo-name-id" href="{% url 'index' %}">
                        <span class="logo-name">PET.er</span>     
                    </a>    
                    <!-- <input class="menu-input" type="text" placeholder="Pesquisar..."> -->
                    <form class="search-container" action="{% url 'pets:search' %}">
                   
                        <input class="menu-input" type="text" name="query" id="id_query" placeholder="Pesquisar..." />                           
                        <button class="search-button" type="submit">Buscar</button>

                    </form>
                </div>

                <div class="menu-top-side menu-right">

                        {% if user.is_authenticated %}
                            <a href="{% url 'pets:lembrete' %}" id="notifica-id" class="round-logo bell-image"> </a> 
                            {% if user.donopet %}
                                {% if user.donopet.imagem %}
                                    <a class="round-logo user-image"
                                    style="background: url('{{ user.donopet.imagem }}') no-repeat center; background-size: cover;" 
                                    id="perfil-id" href = "{% url 'pets:dono' %}"> </a>
                                {% else %}
                                    <a class="round-logo user-image"
                                    style="background: url('../static/icons/User.png') no-repeat center; background-size: cover;" 
                                    id="perfil-id" href = "{% url 'pets:dono' %}"> </a>
                                {% endif %}
                                <span><div class="dropdown"> <!--para fazer dropdown sozinho, precisa dessa classe só de dropdown antes-->
                                
                                <button type="button" class="botao botao-usuario dropdown-toggle" data-toggle="dropdown">
                                    {{ user.username }} <span class="caret"></span></button>
                                    <ul class="dropdown-menu dropdown-peter" role="menu" aria-labelledby="menu1"> <!--dropdown na direita; "role" e "aria" ajudam acessibilidade-->       
                                        <li><a href="{% url 'pets:dono' %}">Perfil</a></li>                                    
                                        <li><a href="{% url 'pets:lembrete' %}">Lembretes</a></li>
                                        <li><a href="{% url 'logout' %}">Sair</a></li>
                                    </ul>
                                </button>
                            {% elif user.veterinario %}
                                {% if user.veterinario.imagem %}
                                    <a class="round-logo user-image" 
                                    style="background: url('{{ user.veterinario.imagem }}') no-repeat center; background-size: cover;"
                                    id="perfil-id" href = "{% url 'pets:vet' %}"> </a>
                                {% else %}
                                    <a class="round-logo user-image" 
                                    style="background: url('../static/icons/User.png') no-repeat center; background-size: cover;"
                                    id="perfil-id" href = "{% url 'pets:vet' %}"> </a>
                                {% endif %}
                                <span><div class="dropdown"> <!--para fazer dropdown sozinho, precisa dessa classe só de dropdown antes-->
                            
                                <button type="button" class="botao botao-usuario dropdown-toggle" data-toggle="dropdown">
                                    {{ user.username }} <span class="caret"></span></button>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1"> <!--dropdown na direita; "role" e "aria" ajudam acessibilidade-->       
                                        <li><a href="{% url 'pets:vet' %}">Perfil</a></li>                                    
                                        <li><a href="{% url 'pets:lembrete' %}">Lembretes</a></li>
                                        <li><a href="{% url 'logout' %}">Sair</a></li>
                                    </ul>
                                </button>
                            {% elif user.clinica %}
                                {% if user.clinica.imagem %}
                                    <a class="round-logo user-image" 
                                    style="background: url('{{ user.clinica.imagem }}') no-repeat center; background-size: cover;"
                                    id="perfil-id" href = "{% url 'pets:clinica' %}"> </a>
                                {% else %}
                                    <a class="round-logo user-image" 
                                    style="background: url('../static/icons/User.png') no-repeat center; background-size: cover;"
                                    id="perfil-id" href = "{% url 'pets:clinica' %}"> </a>
                                {% endif %}
                                <span><div class="dropdown"> <!--para fazer dropdown sozinho, precisa dessa classe só de dropdown antes-->
                            
                                <button type="button" class="botao botao-usuario dropdown-toggle" data-toggle="dropdown">
                                    {{ user.username }} <span class="caret"></span></button>
                                    <ul class="dropdown-menu" role="menu" aria-labelledby="menu1"> <!--dropdown na direita; "role" e "aria" ajudam acessibilidade-->       
                                        <li><a href="{% url 'pets:clinica' %}">Perfil</a></li>                                    
                                        <li><a href="{% url 'pets:lembrete' %}">Lembretes</a></li>
                                        <li><a href="{% url 'logout' %}">Sair</a></li>
                                    </ul>
                                </button>
                            {% else %}
                                <a class="login-button" href="{% url 'logout' %}">Conta incompleta</a>
                            {% endif %}
                        {% else %}
                           <a class="login-button" href="{% url 'login' %}">Login</a>
                        {% endif %}
                    
                    </div></span>
                </div>
            </div>
        </nav>
        <!-- Canto inferior do menu -->
        <nav class="menu-nav">
            <div class="menu-bottom-container">
                <ul class="menu-topics-container" style="height: 35px;">
                    <li>
                        <a class="botao" href="{% url 'pets:enciclopedia' %}">EncicloPETia</a>
                    </li>
                    
                        {% if user.donopet %}
                        <li>|</li>
                        <li>
                        <a class="botao" href="{% url 'pets:petlist' %}">Meus Pets</a>
                        {% elif user.veterinario or user.clinica %}
                        <li>|</li>
                        <li>
                        <a class="botao" href="{% url 'pets:vetlistpets' %}">Meus Clientes e Pets</a>
                        {% endif %}
                        <!-- <div class="dropdown">  -->
                            <!--para fazer dropdown sozinho, precisa dessa classe só de dropdown antes-->
                            <!-- <button type="button" class="botao dropdown-toggle" data-toggle="dropdown">
                                Exames <span class="caret"></span>
                            </button>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="menu1">  -->
                                <!--dropdown na direita; "role" e "aria" ajudam acessibilidade-->
                                <!-- <li class="dropdown-header">Exames realizados</li>
                                <li><a href="#">Exame de sangue</a></li>
                                <li><a href="#">Exame de urina</a></li>     
                            </ul>
                        </div> -->
                    </li>

                </ul>
            </div>
        </nav>
    </header>

    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>

    <footer class="rodape-container">
        <nav class="rodape-nav"><a href="#">Voltar ao começo</a></nav>
        <section class="rodape-main">
            <div class="rodape-topics">
                <div class="centered-topic">
                    <div class="round-logo logo-image"></div>
                    <span class="logo-name">PET.er</span>      
                </div>
                <!-- <div class="centered-topic">            
                    <ul class="menu-topics-container bottom-nav">
                        <li>
                            <a href="">Privacidade</a>                          
                        </li>
                        <li>|</li>
                        <li>
                            <a href="">Ajuda</a>                           
                        </li>
                        <li>|</li>
                        <li>
                            <a href="">Consultar veterinários</a>                         
                        </li>
                        <li>|</li>
                        <li>
                            <a href="">Consultar petshops</a>                         
                        </li>
                        
                    </ul>              
                </div> -->
                <div class="centered-topic bottom-topic">
                    © 2021 PET.er. All Rights Reserved.
                </div>
            </div>
        </section>
    </footer>

</body>

</html>